### ISSUE TITLE
Chem structure is displayed in Structure Viewer

### ISSUE THREAD

**Issue by scilligence** [scilligence/JsHELM#45] opened 2016-10-04 15:47 UTC
Steps to reproduce:
1. Draw a RNA
2. Draw a Chem linking to the RNA
3. Swtich to Structure Viewer, and click the bond connecting RNA and Chem

Bug: the structure of Chem is not displayed

**Comment by tony-yuan** [comment] 2016-10-04 21:27
Fixed

**Comment by ClairePA** [comment] 2016-10-07 08:13
This works for the bond at the 5' end, but clicking the bond at the 3' end does highlight the monomers, but the structure is not shown in the structure box. (I added chems at both ends)
Also, shift clicking phosphate then sugar then base highlights the monomers correctly but the structure display shows the following:
click the phosphate - phosphate is displayed
shift-click the neighbouring sugar - both monomers are highlighted and the structure view shows the sugar only, the phosphate structure is removed
shift-click the base - all three monomers are highlighted and only the sugar structure is displayed.

**Comment by tony-yuan** [comment] 2016-10-11 20:42
Here is the screenshot Claire provided.  The problem is the bond is not selected:
![t](https://cloud.githubusercontent.com/assets/19560173/19287881/94739794-8fd1-11e6-80b1-8331b79c9304.png)

**Comment by ClairePA** [comment] 2016-10-13 12:47
This needs to be added to the user guide as user will assume that selecting the monomers will be sufficient. Please confirm when it is included in the guide.

**Comment by ClairePA** [comment] 2016-10-28 15:39
If you highlight monomers in a peptide but don't select the bond you see the unconnected monomer structures. If you then shift-click the bond you see the monomers connected to each other. This is the correct behaviour. 
If you highlight multiple nucleotide monomers, but don't select the bond you only see one unconnected monomer structure. The behaviour for nucleotides should be the same as peptides.

**Comment by tony-yuan** [comment] 2016-11-01 19:46
Fixed in 2016-11-02 update

**Comment by ClairePA** [comment] 2016-11-02 10:40
Stes to reproduce:
Click on R then shift-click A
![image](https://cloud.githubusercontent.com/assets/3986896/19925532/46b25b08-a0e8-11e6-93fd-140da1ceebb4.png)
only the sugar is shown in the structure view
![image](https://cloud.githubusercontent.com/assets/3986896/19925537/4c61744e-a0e8-11e6-9408-b72c3fd0c8c6.png)
Click on A then shift-click R gives the same display

Click on R then shift-click on P and you get the separate monomer which is correct, but they are too close together
![image](https://cloud.githubusercontent.com/assets/3986896/19925601/8f6cad62-a0e8-11e6-83dd-ada619e28375.png)

Shift-clicking the aminoacids in a peptide now gives the separate monomers (correct), but they are also overlaid.
![image](https://cloud.githubusercontent.com/assets/3986896/19925626/b1286df6-a0e8-11e6-9cf1-01720f34af67.png)
![image](https://cloud.githubusercontent.com/assets/3986896/19925631/b7482a96-a0e8-11e6-8973-3ca6cedf0a06.png)

**Comment by ClairePA** [comment] 2016-12-02 15:18
When you select adjacent monomers, the bond between them should also be selected. Therefore the monomers will be displayed as joined together. 
Non adjacent monomers will remain separate.

**Comment by scilligence** [comment] 2016-12-08 18:23
fixed in 2016-12-08 update

**Comment by ClairePA** [comment] 2016-12-09 10:12
Confirmed fixed. Looks great!

**Closed by ClairePA** 2016-12-09 10:12 UTC
